---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: telperion
# description will be included in the image's metadata
description: Custom image on top of Fedora Sway Atomic.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ghcr.io/wayblueorg/sway
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://repo.vivaldi.com/archive/vivaldi-fedora.repo
    install:
      - neovim
      - fish
      - vivaldi-stable
    optfix:
      - vivaldi
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      - android-tools
      - gnome-themes-extra
      - gnome-icon-theme
      - paper-icon-theme
      # - breeze-icon-theme
      # - papirus-icon-theme
      - sddm
      - sddm-themes
      - sddm-wayland-sway

  - type: systemd
    system:
      enabled:
        - sddm-boot.service

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
        - com.slack.Slack
      remove:
        - org.gnome.Loupe
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: bling
    install:
      - 1password # install 1Password (stable) and `op` CLI tool

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

